### ISSUE TITLE
[resolved] Tag the master branch to mark the version as stable for composer

### ISSUE THREAD

**Issue by michallohnisky** [SimonEast/Simple-Ansi-Colors#2]
Hi,

could you please tag the master branch to mark the version as stable for composer? Here is the manual: https://help.github.com/articles/creating-releases/ .

Thanks.

**Comment by SimonEast** [comment]
Thanks @michallohnisky. I've created a release for version 1.0.0.  I hope that does what's needed.

**Comment by michallohnisky** [comment]
@SimonEast Thx.
